import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.Map;

import org.testng.Assert;
import org.testng.annotations.Test;

/**
 * Test suite for the Anagram class.
 * <p>
 * The provided test suite is correct and complete. You should not need to modify it. However, you
 * should understand it. You will need to augment or write test suites for later MPs.
 *
 * @see <a href="https://cs125.cs.illinois.edu/MP/2/">MP2 Documentation</a>
 */
public class AnagramTest {

    /**
     * Timeout for our tests. Solution takes 48 ms.
     */
    private static final int TEST_TIMEOUT = 480;

    /**
     * Test with precomputed values.
     */
    @Test(timeOut = TEST_TIMEOUT)
    public void testAreAnagrams() {
        for (Map.Entry<ArrayList<String>, Boolean> precomputed : PRECOMPUTED_RESULTS.entrySet()) {
            ArrayList<String> input = precomputed.getKey();
            Boolean output = precomputed.getValue();

            Assert.assertEquals(Anagram.areAnagrams(input.get(0), input.get(1)), (boolean) output,
                    "Incorrect result for " + input.get(0) + " and " + input.get(1));
        }
    }

    /**
     * Pre-computed testing values.
     */
    private static final Map<ArrayList<String>, Boolean> PRECOMPUTED_RESULTS =
            new LinkedHashMap<>() {
                {
                    put(new ArrayList<>() {
                        {
                            add(null);
                            add(null);
                        }
                    }, false);
                    put(new ArrayList<>() {
                        {
                            add(null);
                            add("");
                        }
                    }, false);
                    put(new ArrayList<>() {
                        {
                            add("");
                            add(null);
                        }
                    }, false);
                    put(new ArrayList<>() {
                        {
                            add("");
                            add("");
                        }
                    }, true);

                    put(new ArrayList<>() {
                        {
                            add("ABA");
                            add("aba");
                        }
                    }, true);
                    put(new ArrayList<>() {
                        {
                            add("ABA");
                            add("a b a");
                        }
                    }, true);
                    put(new ArrayList<>() {
                        {
                            add("Test me!");
                            add("Me, test.");
                        }
                    }, true);
                    put(new ArrayList<>() {
                        {
                            add("Test me!");
                            add("Me, best.");
                        }
                    }, false);
                    put(new ArrayList<>() {
                        {
                            add("Test test!");
                            add("Test.");
                        }
                    }, false);
                    /* BEGIN AUTOGENERATED CODE */
                    put(new ArrayList<>() {
                        {
                            add("rru1U96i31m8kDkMwllhrvcjSgCVb0165rWiaxTo0cbOkZH0YMS");
                            add("9rST,gM-8SUiaQltbOocVh06brk610mk50,3Yw1.11x.CujncWjHoDMv");
                        }
                    }, false);
                    put(new ArrayList<>() {
                        {
                            add("8IAThsxvJKKa90rZK5ZbjviWzy6tgH3kCFXTnzL8IeP3v4q6M1VGN3k");
                            add("NIKzAX8aK6F3v. rZr1t9.a^G0WyvMHPkMn6hj5zCgx4iK3IbLV3TvZ8qTs");
                        }
                    }, false);
                    put(new ArrayList<>() {
                        {
                            add("8b0PmM45cK");
                            add("m8bcPKM450");
                        }
                    }, true);
                    put(new ArrayList<>() {
                        {
                            add("zilOiEPRdPWtVm8jCoQ");
                            add("F8PzVlC t6PdlE,Q-tlij.m");
                        }
                    }, false);
                    put(new ArrayList<>() {
                        {
                            add("3n4EqHEIGfLlshMmhlZhejUX7r");
                            add("Uf4sL!eEHh,ZIX! l,!nj37MGhlhqEmr");
                        }
                    }, true);
                    put(new ArrayList<>() {
                        {
                            add("TnyF4aGI48YWRljYdljfnD1Um");
                            add("F.Y84Id^GYjaW,U1llD^Rnym4jTfn");
                        }
                    }, true);
                    put(new ArrayList<>() {
                        {
                            add("vh4Rrvcn65WABX1ijISFLMTYsb01FXUsJHm4vBMhmu8aJQSl0UmynoljbWWY");
                            add("lSnRsU8moYhjHSXFjb460Mv1LBWiavh-XAQJTWclUmWMnr4Ibu05BFvm1YysJ");
                        }
                    }, true);
                    put(new ArrayList<>() {
                        {
                            add("a1S8s5BzTbCj3q4ZACmBfnXb");
                            add("f8C1SXjz5^qasbm4BT^CBbA3nZ");
                        }
                    }, true);
                    put(new ArrayList<>() {
                        {
                            add("HxoC2RzdWxtTvUity");
                            add(" -ytxCdz!H!Utf2vi-7Rxo");
                        }
                    }, false);
                    put(new ArrayList<>() {
                        {
                            add("uXQZb3UsDTDuGGN");
                            add("LpbGD7,FsZ^U  uUTGD");
                        }
                    }, false);
                    put(new ArrayList<>() {
                        {
                            add("TAq5AbtoIVodjksDXUqADfmI1DLrnl1oOxgPvbeZV2grKan65chBN6MMVeP0F3f");
                            add("1DcaKe5IUhd162fLklxoBobm0qADTq3gZbrjsF5PV,VVMMonIeDfrANtvCAOXnP6");
                        }
                    }, false);
                    put(new ArrayList<>() {
                        {
                            add("wN5KTZwkdKjRoujy2RG1uhXizrcdxmTmqQIvTK71wNRpRI5kcWgmibD41qrAI");
                            add("cmQTxdG1brwiqIhNXu1QtvDku,c4qRTjRjKw.-IyI7jeKk5mTd2rKoNwm!ZzgRW51");
                        }
                    }, false);
                    put(new ArrayList<>() {
                        {
                            add("Fpslg6rpE0CFTYOwgY3qJZjQINWRkWWNkzV01hjiboNnfh9XJct1CiSpuaAiMiD");
                            add("ZgQlTg1inY2k0fCbFS jb uW0kiXoj9hOFJ6hiiMrctDpC,RqzIKpNwWE,WNAaJY1,Vq");
                        }
                    }, false);
                    put(new ArrayList<>() {
                        {
                            add("IqkL19oZjonqT0Zk9rjlo8bn8pFoEB9XEm6j77DlICOVL7rMiirbLoG5k");
                            add("oEoXnlDZ.kF06rp7L9o8i,LBjk7moGbqVIIrkjoLE51iM,9lqrO89-Z7j!CTnb");
                        }
                    }, true);
                    put(new ArrayList<>() {
                        {
                            add("qFxCXDSR2b95oZdkGx0xRSr89yvCbqCXJd09pz");
                            add("Dq99CX8ROxxbGzbr!RJdd2XC!5ypZ0Sovk!0SzqFx");
                        }
                    }, false);
                    put(new ArrayList<>() {
                        {
                            add("cqRCJJcxrU0LRpbl6UiNsqW4zt0ZcV6NenSC");
                            add("N6nJZRzb4VqRlqNccpCeiscUSJ0Wx06rLUCt");
                        }
                    }, true);
                    put(new ArrayList<>() {
                        {
                            add("5grd4CBivpCmUBGqqCFPIxETi7FpIUXkv9q9wmFF");
                            add("5FpwqCv4kUg-,7.qFUdgCiF9Pi^!IwX.Bx,,ECITBp7dmmrG");
                        }
                    }, false);
                    put(new ArrayList<>() {
                        {
                            add("UL21UCkCvolMWDXV2QERX9z5pw9dpuIYsjKzFfTGWj2c3C");
                            add("QUc2CsEjWjCwX-^pUzMID,f97Y2^TC2k-.l5X1GzdRoDpFuV3vK9");
                        }
                    }, false);
                    put(new ArrayList<>() {
                        {
                            add("qvvyJrlW0q3Ovnr8H12y10eFfpeFwm5vVefnooJF3pyMMdNXhyPaUeo");
                            add("vpN1.elyrFFov5pd,VmX2nOrM0MFaqoPe3eJy3n-8JUwq hopyv0HfysbW1");
                        }
                    }, false);
                    put(new ArrayList<>() {
                        {
                            add("2ELzElFXUSZzTOX1JAG4pVuuFkC814eOK93TlNdJVhQbwn1RWHhppyxznFTjOAM");
                            add("lWQJn34wCxFeTHWBFMl91XuAUzCThdZjAuU1bpE,VzVOEGzXIOF.KNTLJpkSRy1h2");
                        }
                    }, false);
                    put(new ArrayList<>() {
                        {
                            add("3EMkh2fVDxLkp2Sp0JTPgLwyPg9vlfrMSNeuHr");
                            add(" JfHLrTuN32DlMMkpS9rgPepS.fEyxV20vP,-w.hk^gL");
                        }
                    }, true);
                    put(new ArrayList<>() {
                        {
                            add("MYIhwvwBJCHdNE4fFyRgKqJ6iRKNGZ2cHJ3hXpntyd3vY");
                            add("YHpBXtZ.KKNGdqc3 iAHkyNv6hwYMv3y.fEIhR2L4JJJdwFC");
                        }
                    }, false);
                    put(new ArrayList<>() {
                        {
                            add("xx4IiXlsa6P9ZQ3osg304TvujUprCKi3iE");
                            add("6pTg4s-iKsaXirlExxouIP3^943QvZiUC-j03,");
                        }
                    }, true);
                    put(new ArrayList<>() {
                        {
                            add("Vk4uK6zLJHU6HZgAy15dlosc2etjUiE9XJ18PRJaqTFJLDxleY");
                            add("2Dgiu6e2JkJtZyL H1d,9E6Vo1U5jjTLhZFz4axP3Jl!eoUYcKlRJ");
                        }
                    }, false);
                    put(new ArrayList<>() {
                        {
                            add("rljJPoIXeEAtLkwuMf8hSJgv15eqhAmfEidK970hCGMxLIl");
                            add("L!Gw0qMgXxhIjvJd-LeEPffh uCM8-71lhtCoI.EAmk5rAUlJ-eoi");
                        }
                    }, false);
                    put(new ArrayList<>() {
                        {
                            add("Pl0xN9jxAhyYckPLuqFzOUNwEN");
                            add("Oyhx^LwPq,ky.zyFLcx0EjNYNl-m.AU");
                        }
                    }, false);
                    put(new ArrayList<>() {
                        {
                            add("FauI4rst2Du3G3RsrB1kVTww");
                            add("RVF1Gwt3-a2k4,BsDIuTus wrr3 ");
                        }
                    }, true);
                    put(new ArrayList<>() {
                        {
                            add("IpIyJhi7YxO9ZssreFI6ho3ioT3C5ozyvsgwncVfh2khKQsUv2n6YZxvmORl9");
                            add("ge9 ,6ozZIOksxxs6sw5ylIZYnvQJUycp,3vmY72hVO92-KioIsRCF oriT 3fhvhh^n");
                        }
                    }, true);
                    put(new ArrayList<>() {
                        {
                            add("HhbXezVez");
                            add("eezhbzVHX^");
                        }
                    }, true);
                    put(new ArrayList<>() {
                        {
                            add("4cP7vJS96r6uGMbrbFxGhRIsFQgt7QJ8SHnMyUOm8w0cFKJS");
                            add("vw8tSFjQ7H4reImhcJR,yMd6PFn^K7!,sJ!^CSFbG9Jxg8c-S6OUGMQ");
                        }
                    }, false);
                    put(new ArrayList<>() {
                        {
                            add("bVty1rEM");
                            add("1-r -b -t^.!VEMy");
                        }
                    }, true);
                    put(new ArrayList<>() {
                        {
                            add("Xrqu1MQB");
                            add("q.BMu..9.QX1");
                        }
                    }, false);
                    put(new ArrayList<>() {
                        {
                            add("8QoRDjyHw2qqirbzThwOU6scZ0LnqfqERiOqEq3C5MLsBvonIiwr");
                            add("TCvqwL0iZEEqcUr,ohoQiMqqO3wfqDz-nbjR2RiLs8.OqnwyB^Hr56Is");
                        }
                    }, true);
                    put(new ArrayList<>() {
                        {
                            add("HQWixJmyyJbZIH");
                            add("Sm, !cnH xJ!HQ^yb i.dv");
                        }
                    }, false);
                    put(new ArrayList<>() {
                        {
                            add("p5fZgBazd14IXYEiA3uGcQVxizjqUv");
                            add("4clixGI1!,5q,YEVpJfj3zQvBUuZg,A-yai");
                        }
                    }, false);
                    put(new ArrayList<>() {
                        {
                            add("BNedQNoqBpnOEn9oCEdr7LJK7F4qnIQB5FxFuBm5cBWqTf7PIe3yeY6PnG");
                            add("5.e9Y6e.WBzqPBcO.!dFLnBC74yEeo9nIFB^mx!5Q!roEN,qdpA7PnunGn3FNKfQqB");
                        }
                    }, false);
                    put(new ArrayList<>() {
                        {
                            add("SggVHuYA4BS9SPaAryLjQuDxNL8krfilJfDGXd3HT");
                            add("DNgTiAfQS4G- H9^3XLgVAySPurufrL,aljdJS!^kx.YHB8-D");
                        }
                    }, true);
                    put(new ArrayList<>() {
                        {
                            add("bQmR7de9bEFVA10STdS1zMl0fFqjn");
                            add("d!-M 9TfFj7bFenz1b, !qd0SmRAVS1l0QE,,");
                        }
                    }, true);
                    put(new ArrayList<>() {
                        {
                            add("wm4WEQrbY");
                            add(" ! EWm,4-r!wQbY,");
                        }
                    }, true);
                    put(new ArrayList<>() {
                        {
                            add("WCEjkia32Pq5dmHXtxVGlwumaPqqnRX");
                            add("2iqPqqxlwWC-ERdVX G5HtkX31muP0anm,");
                        }
                    }, false);
                    put(new ArrayList<>() {
                        {
                            add("gsekYiUC7Gcsh5FOXa9RGSFDpbx5j94a4sX55ze1JeTO4r2CIdfanuI7eH");
                            add("9JzGu5L2indI5eC4Y.GyEp 5r-sU9gFX5^DehsX,bex1SHROdCe1agja7sIkFa4");
                        }
                    }, false);
                    put(new ArrayList<>() {
                        {
                            add("ufgEyGYM3FlUaCTiHHkVniOUbOJunba9bfcOGhvX3AWq0wCvupp1X01SoecT");
                            add("9gMcX!bvF VhlfCv1Y3JWkSHUTbU-G!bici3ypnnf0wA,.aaHXu.eCGTO01pOOquEou");
                        }
                    }, true);
                    put(new ArrayList<>() {
                        {
                            add("jE2oIxKpj06mzIrloMDoXERXNHXiRieRSsJk2C3p1Nv80lRjzO791z");
                            add("O6voD2ERIIel0RM8!Nzi2sjKpJRCmEkj-rzXilpd3ozxS4X0X1jH1oR9");
                        }
                    }, false);
                    put(new ArrayList<>() {
                        {
                            add("rBiyZB17fg6E3teLgLHaOpGpLaQRbjw5ob7ewKgqEji");
                            add("E!eQgw-ip1B67ob-jBErgLZe iGyjgKORtLaHbf.7pw3qLa5");
                        }
                    }, true);
                    put(new ArrayList<>() {
                        {
                            add("AW1jsWk3GAax5pDyLOTXjuTVvaBa1Xl5cRj6COc55Av8NVsmDzagSfz6uReyswRv");
                            add("5msW-w5AjkT.a8fsG5jS6OcWA1DpzvNCa6ljusycKR-^!V1BgvTaz,vyD3gU,RseLaOVrAX^");
                        }
                    }, false);
                    put(new ArrayList<>() {
                        {
                            add("89n8OGpcYt0U6jBHhmMyqVs9eov");
                            add("hY-jG 9q9yVmnfqOB- Goc8Uc0^,s e-t86");
                        }
                    }, false);
                    put(new ArrayList<>() {
                        {
                            add("X09eGhuFHQKhYk2Qmkn8TzmjMgF18szDlq0De3xKsigTENZ9ojvpKsy");
                            add("sHZgq3um0xhF KEz9Kz2zhvTgihDQak0GKXEQ3njmsvY981peose9kTl");
                        }
                    }, false);
                    put(new ArrayList<>() {
                        {
                            add("ZKWirUISf0I");
                            add("WU.SK0fiZIrI");
                        }
                    }, true);
                    put(new ArrayList<>() {
                        {
                            add("FwbTiQQIbNii0mX3K1V86XMTWssL60qLDfdwTtMVF3UHG");
                            add("8VKT0swH6GLq1LFi-Vi 3tbm0TDMWTQNCb!sIXd0MX6-3.UsFw.");
                        }
                    }, false);
                    put(new ArrayList<>() {
                        {
                            add("xqDOkPFD3hjaGmdrGrvkTJLTKsbMXIaOYymscxGVCQB2lD8eipBoCT");
                            add("plgBX3Gamjs! mDa.FTChBMdSxqsDvIR8GokQrO-kiDVvCeOG,a 2JrKTbxL");
                        }
                    }, false);
                    put(new ArrayList<>() {
                        {
                            add("T94wVm4qkQ7ypeiWDracFhcpfWSZ");
                            add("Smy,Q!4,,Deppr7-iZa4FkhcqV.W9cWwfT!");
                        }
                    }, true);
                    put(new ArrayList<>() {
                        {
                            add("i3er6H1gYAFlKfZKmm2");
                            add(".FZr^g-3e^1Ki6,mKAmY!fC,^H2");
                        }
                    }, false);
                    put(new ArrayList<>() {
                        {
                            add("eB0Yf2QeHl72exUDVdboHMozUCzM");
                            add(",f-ezbx7CMH YQoeU2lzV^B.0dUe2DoHM");
                        }
                    }, true);
                    put(new ArrayList<>() {
                        {
                            add("AzOHPCzR2o1iEupk4uXCSp08LIQbSoD5FxHzhn0QO8NI7yVTayVKHdUWTVuj2q4");
                            add("z87-p-k-Rxb,0qAuHyaPE-Q1,^WhkI4zOS5jLS2O2dQuyHIXCDzU^NoVFCupIVVoi0VT8cn");
                        }
                    }, false);
                    put(new ArrayList<>() {
                        {
                            add("gYYQLXWozQhqmnDGN6mAamHaf3");
                            add("aqanmzmWD^m6QGQ,Xot^.fI!NdA3Lgh");
                        }
                    }, false);
                    put(new ArrayList<>() {
                        {
                            add("9VYYzJOZArzZJJwPJz");
                            add("ZP,ZJz-A.Ow!iFzY8-Jz!BKa");
                        }
                    }, false);
                    put(new ArrayList<>() {
                        {
                            add("pg7NEgxAzbRtz2OynQ5");
                            add("gMNx57Ozyt3zFRb2n5E");
                        }
                    }, false);
                    put(new ArrayList<>() {
                        {
                            add("flfvuVdjWEfhixgCqIyZmnOuwKcuM9a2jUv0FhYWV");
                            add("oOa!ZnIVUjuvfjYPWu2i!vf!KFfuV9wWdxMlcCmj!hEhy");
                        }
                    }, false);
                    put(new ArrayList<>() {
                        {
                            add("sLjyv90fYz2XvMsAzXSiij2zwqUK0WphXOlLt2N0ZfBTVu");
                            add("pjyfjLMz!VAY0tWOih0,fiUB!L2rXsTKXuz,S9.2Xwb^zsfqlvZ2");
                        }
                    }, false);
                    put(new ArrayList<>() {
                        {
                            add("L5sQ6t6CPhO6ed5sk");
                            add("6Odk.tC7Q5eLMMQxU 6");
                        }
                    }, false);
                    put(new ArrayList<>() {
                        {
                            add("ihIo5zKIcJJ5jWa83zIcydJUYP5j1dTSeyuKdFVrT7sKWiUJpFHWD4qcfI");
                            add("zJVcsUh5p-K17P4IIHST5yFJDcz,ruiedJ3cK5JKYUyjj8fWdWW^idoaTqII-F");
                        }
                    }, true);
                    put(new ArrayList<>() {
                        {
                            add("Y8mv0M8EodpVx4mbuSR4");
                            add("Sd0pbV8o8YRmMEum4vx4");
                        }
                    }, true);
                    put(new ArrayList<>() {
                        {
                            add("6kJhL3ynUAPGUYpfnmws");
                            add("AU3-U3sJnGp f,6yhmkYULP");
                        }
                    }, false);
                    put(new ArrayList<>() {
                        {
                            add("NyFbYL8WeWf8xy");
                            add("L88-bF^efWyN,xy WY");
                        }
                    }, true);
                    /* END AUTOGENERATED CODE */
                }
            };
}
