/*
 * SpoonacularAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.mashape.p.spoonacularrecipefoodnutritionv1;

import android.content.Context;

import android.content.pm.ApplicationInfo;
import android.content.pm.PackageManager;
import android.os.Bundle;

import com.android.volley.RequestQueue;
import com.android.volley.toolbox.Volley;

public class Configuration {
    /**
     * The base Uri for API calls
     */
    public static String baseUri = "https://spoonacular-recipe-food-nutrition-v1.p.mashape.com";

    /**
     * Initialize configuration and HTTP client request queue
     * @param context Application context
     */
    public static void initialize(Context context){

        requestQueue = Volley.newRequestQueue(context);
        String packageName = context.getPackageName();
        PackageManager packageManager = context.getPackageManager();
        try {
            ApplicationInfo app = packageManager.getApplicationInfo(packageName, PackageManager.GET_META_DATA);
            Bundle bundle = app.metaData;

            if(bundle != null) {
                if(bundle.containsKey("xmashapekey"))
                    xMashapeKey = bundle.get("xmashapekey").toString();

            }

            initialized = true;
        }
        catch (Exception ex){
            throw new IllegalStateException("Unable to initialize", ex);
        }
    }

    /**
     * Get HTTP client request queue
     * @return Request queue
     */
    public static RequestQueue getRequestQueue() {
        if(!initialized)
            throw new IllegalStateException("Must initialize before accessing request queue");
        return requestQueue;
    }
    
    /**
     * Get xMashapeKey
     * @return The Mashape application you want to use for this session.
     */
    public static String getXMashapeKey() {
        if(!initialized)
            throw new IllegalStateException("Must initialize configuration before use");

        return xMashapeKey;
    }

    /**
     * Set value for xMashapeKey
     * @param xMashapeKey TODO: Add description
     */
    public static void setXMashapeKey(String xMashapeKey) {
        Configuration.xMashapeKey = xMashapeKey;
    }


    /**
     * Retains status whether we have already initialized
     */
    private static boolean initialized = false;

    /** 
     * Request queue for http client
     */
    private static RequestQueue requestQueue = null;

    /**
     * Private backing field for XMashapeKey
     */
    private static String xMashapeKey = null;

}
