# Generated by Django 2.1.1 on 2018-09-16 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_name', models.CharField(max_length=64)),
                ('hardware_serial', models.CharField(max_length=64)),
                ('remote_address', models.CharField(max_length=16)),
                ('wlan_address', models.CharField(max_length=16)),
                ('wlan_mac', models.CharField(max_length=24)),
                ('lan_address', models.CharField(max_length=16)),
                ('lan_mac', models.CharField(max_length=24)),
                ('last_ping', models.DateTimeField(verbose_name='last ping received')),
            ],
        ),
    ]
