# Generated by Django 2.1.1 on 2018-09-16 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pistatus', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pi',
            name='id',
        ),
        migrations.AlterField(
            model_name='pi',
            name='hardware_serial',
            field=models.CharField(max_length=64, primary_key=True, serialize=False),
        ),
    ]
