# Generated by Django 2.1.1 on 2018-09-16 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pistatus', '0002_auto_20180916_1709'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pi',
            name='lan_mac',
        ),
        migrations.RemoveField(
            model_name='pi',
            name='wlan_mac',
        ),
    ]
