# Generated by Django 2.1.1 on 2018-09-17 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pistatus', '0003_auto_20180916_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='pi',
            name='public_routable',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pi',
            name='lan_address',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='pi',
            name='wlan_address',
            field=models.CharField(max_length=16, null=True),
        ),
    ]
