import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.Map;
import org.testng.Assert;
import org.testng.annotations.Test;

/**
 * Test suite for the LCM class.
 * <p>
 * The provided test suite is correct and complete. You should not need to modify it. However, you
 * should understand it. You may need to augment or write test suites for later MPs.
 *
 * @see <a href="https://cs125.cs.illinois.edu/MP/0/">MP0 Documentation</a>
 */
@Test
public class LCMTest {

    /** Testing timeout. Solution takes 96 ms. */
    private static final int TEST_TIMEOUT = 1000;

    /**
     * Test with precomputed values.
     */
    @Test(timeOut = TEST_TIMEOUT)
    public void test() {
        for (Map.Entry<ArrayList<Integer>, Integer> precomputed : PRECOMPUTED_RESULTS.entrySet()) {
            ArrayList<Integer> input = precomputed.getKey();
            Integer output = precomputed.getValue();

            /*
             * Check LCM in both directories.
             */
            Assert.assertEquals(LCM.lcm(input.get(0), input.get(1)),
                    (int) output,
                    String.format("LCM of %d and %d is incorrect", input.get(0), input.get(1)));
            Assert.assertEquals(LCM.lcm(input.get(1), input.get(0)),
                    (int) output,
                    String.format("LCM of %d and %d is incorrect", input.get(0), input.get(1)));
        }
    }

    /** Pre-computed testing values. */
    private static final Map<ArrayList<Integer>, Integer> PRECOMPUTED_RESULTS =
            new LinkedHashMap<ArrayList<Integer>, Integer>() {
                {
                    put(new ArrayList<Integer>() {
                        {
                            add(6);
                            add(4);
                        }
                    }, 12);
                    put(new ArrayList<Integer>() {
                        {
                            add(-6);
                            add(3);
                        }
                    }, 6);
                    put(new ArrayList<Integer>() {
                        {
                            add(0);
                            add(4);
                        }
                    }, LCM.LCM_INVALID);
                    put(new ArrayList<Integer>() {
                        {
                            add(6);
                            add(0);
                        }
                    }, LCM.LCM_INVALID);
                    /* BEGIN AUTOGENERATED CODE */
                    put(new ArrayList<Integer>() {
                        {
                            add(552);
                            add(-2282);
                        }
                    }, 629832);
                    put(new ArrayList<Integer>() {
                        {
                            add(25465);
                            add(-10350);
                        }
                    }, 52712550);
                    put(new ArrayList<Integer>() {
                        {
                            add(-32549);
                            add(-1067);
                        }
                    }, 3157253);
                    put(new ArrayList<Integer>() {
                        {
                            add(-21664);
                            add(-1822);
                        }
                    }, 19735904);
                    put(new ArrayList<Integer>() {
                        {
                            add(10450);
                            add(17745);
                        }
                    }, 37087050);
                    put(new ArrayList<Integer>() {
                        {
                            add(-21823);
                            add(-12119);
                        }
                    }, 264472937);
                    put(new ArrayList<Integer>() {
                        {
                            add(-6074);
                            add(18867);
                        }
                    }, 114598158);
                    put(new ArrayList<Integer>() {
                        {
                            add(29135);
                            add(23834);
                        }
                    }, 694403590);
                    put(new ArrayList<Integer>() {
                        {
                            add(21059);
                            add(15596);
                        }
                    }, 328436164);
                    put(new ArrayList<Integer>() {
                        {
                            add(-18337);
                            add(26947);
                        }
                    }, 494127139);
                    put(new ArrayList<Integer>() {
                        {
                            add(-27835);
                            add(25142);
                        }
                    }, 699827570);
                    put(new ArrayList<Integer>() {
                        {
                            add(17743);
                            add(10190);
                        }
                    }, 180801170);
                    put(new ArrayList<Integer>() {
                        {
                            add(3983);
                            add(26389);
                        }
                    }, 105107387);
                    put(new ArrayList<Integer>() {
                        {
                            add(-27835);
                            add(15527);
                        }
                    }, 432194045);
                    put(new ArrayList<Integer>() {
                        {
                            add(-26519);
                            add(31793);
                        }
                    }, 843118567);
                    put(new ArrayList<Integer>() {
                        {
                            add(31411);
                            add(7891);
                        }
                    }, 247864201);
                    put(new ArrayList<Integer>() {
                        {
                            add(-16871);
                            add(-12290);
                        }
                    }, 207344590);
                    put(new ArrayList<Integer>() {
                        {
                            add(27315);
                            add(-10486);
                        }
                    }, 286425090);
                    put(new ArrayList<Integer>() {
                        {
                            add(1975);
                            add(-32537);
                        }
                    }, 64260575);
                    put(new ArrayList<Integer>() {
                        {
                            add(-3779);
                            add(19142);
                        }
                    }, 72337618);
                    put(new ArrayList<Integer>() {
                        {
                            add(-11647);
                            add(-15998);
                        }
                    }, 9806774);
                    put(new ArrayList<Integer>() {
                        {
                            add(-15638);
                            add(-30485);
                        }
                    }, 68103490);
                    put(new ArrayList<Integer>() {
                        {
                            add(9284);
                            add(-21000);
                        }
                    }, 48741000);
                    put(new ArrayList<Integer>() {
                        {
                            add(-5440);
                            add(2472);
                        }
                    }, 1680960);
                    put(new ArrayList<Integer>() {
                        {
                            add(29751);
                            add(-14577);
                        }
                    }, 144560109);
                    put(new ArrayList<Integer>() {
                        {
                            add(19417);
                            add(2726);
                        }
                    }, 52930742);
                    put(new ArrayList<Integer>() {
                        {
                            add(29432);
                            add(-21612);
                        }
                    }, 159021096);
                    put(new ArrayList<Integer>() {
                        {
                            add(-27847);
                            add(6855);
                        }
                    }, 190891185);
                    put(new ArrayList<Integer>() {
                        {
                            add(10061);
                            add(-31350);
                        }
                    }, 315412350);
                    put(new ArrayList<Integer>() {
                        {
                            add(28692);
                            add(19293);
                        }
                    }, 184518252);
                    put(new ArrayList<Integer>() {
                        {
                            add(-6913);
                            add(11015);
                        }
                    }, 76146695);
                    put(new ArrayList<Integer>() {
                        {
                            add(3373);
                            add(9648);
                        }
                    }, 32542704);
                    put(new ArrayList<Integer>() {
                        {
                            add(11682);
                            add(-18392);
                        }
                    }, 9766152);
                    put(new ArrayList<Integer>() {
                        {
                            add(-23767);
                            add(6178);
                        }
                    }, 146832526);
                    put(new ArrayList<Integer>() {
                        {
                            add(30560);
                            add(-19431);
                        }
                    }, 593811360);
                    put(new ArrayList<Integer>() {
                        {
                            add(-11634);
                            add(-24882);
                        }
                    }, 48246198);
                    put(new ArrayList<Integer>() {
                        {
                            add(22077);
                            add(17523);
                        }
                    }, 3907629);
                    put(new ArrayList<Integer>() {
                        {
                            add(28048);
                            add(24841);
                        }
                    }, 696740368);
                    put(new ArrayList<Integer>() {
                        {
                            add(-26532);
                            add(-10324);
                        }
                    }, 68479092);
                    put(new ArrayList<Integer>() {
                        {
                            add(-25019);
                            add(23012);
                        }
                    }, 575737228);
                    put(new ArrayList<Integer>() {
                        {
                            add(-29796);
                            add(2853);
                        }
                    }, 28335996);
                    put(new ArrayList<Integer>() {
                        {
                            add(-17206);
                            add(-19046);
                        }
                    }, 163852738);
                    put(new ArrayList<Integer>() {
                        {
                            add(-16103);
                            add(4514);
                        }
                    }, 72688942);
                    put(new ArrayList<Integer>() {
                        {
                            add(-7546);
                            add(5967);
                        }
                    }, 45026982);
                    put(new ArrayList<Integer>() {
                        {
                            add(-25838);
                            add(4012);
                        }
                    }, 51831028);
                    put(new ArrayList<Integer>() {
                        {
                            add(23321);
                            add(24758);
                        }
                    }, 577381318);
                    put(new ArrayList<Integer>() {
                        {
                            add(13392);
                            add(1915);
                        }
                    }, 25645680);
                    put(new ArrayList<Integer>() {
                        {
                            add(-14713);
                            add(-1522);
                        }
                    }, 22393186);
                    put(new ArrayList<Integer>() {
                        {
                            add(-26857);
                            add(25763);
                        }
                    }, 691916891);
                    put(new ArrayList<Integer>() {
                        {
                            add(8084);
                            add(4465);
                        }
                    }, 767980);
                    put(new ArrayList<Integer>() {
                        {
                            add(18388);
                            add(10314);
                        }
                    }, 94826916);
                    put(new ArrayList<Integer>() {
                        {
                            add(-27772);
                            add(29127);
                        }
                    }, 808915044);
                    put(new ArrayList<Integer>() {
                        {
                            add(-30473);
                            add(-6273);
                        }
                    }, 191157129);
                    put(new ArrayList<Integer>() {
                        {
                            add(-20002);
                            add(20650);
                        }
                    }, 206520650);
                    put(new ArrayList<Integer>() {
                        {
                            add(31200);
                            add(661);
                        }
                    }, 20623200);
                    put(new ArrayList<Integer>() {
                        {
                            add(-13129);
                            add(19876);
                        }
                    }, 260952004);
                    put(new ArrayList<Integer>() {
                        {
                            add(20694);
                            add(-32176);
                        }
                    }, 332925072);
                    put(new ArrayList<Integer>() {
                        {
                            add(24328);
                            add(-28150);
                        }
                    }, 342416600);
                    put(new ArrayList<Integer>() {
                        {
                            add(-2153);
                            add(-398);
                        }
                    }, 856894);
                    put(new ArrayList<Integer>() {
                        {
                            add(14993);
                            add(-24663);
                        }
                    }, 369772359);
                    put(new ArrayList<Integer>() {
                        {
                            add(-7893);
                            add(-2274);
                        }
                    }, 5982894);
                    put(new ArrayList<Integer>() {
                        {
                            add(-29242);
                            add(19987);
                        }
                    }, 584459854);
                    put(new ArrayList<Integer>() {
                        {
                            add(28251);
                            add(1583);
                        }
                    }, 44721333);
                    put(new ArrayList<Integer>() {
                        {
                            add(-27348);
                            add(-1406);
                        }
                    }, 19225644);
                    put(new ArrayList<Integer>() {
                        {
                            add(1346);
                            add(-21958);
                        }
                    }, 14777734);
                    put(new ArrayList<Integer>() {
                        {
                            add(28820);
                            add(-32025);
                        }
                    }, 184592100);
                    put(new ArrayList<Integer>() {
                        {
                            add(-26309);
                            add(-12354);
                        }
                    }, 325021386);
                    put(new ArrayList<Integer>() {
                        {
                            add(-344);
                            add(-6354);
                        }
                    }, 1092888);
                    put(new ArrayList<Integer>() {
                        {
                            add(-16925);
                            add(17820);
                        }
                    }, 60320700);
                    put(new ArrayList<Integer>() {
                        {
                            add(-28573);
                            add(32025);
                        }
                    }, 915050325);
                    put(new ArrayList<Integer>() {
                        {
                            add(25647);
                            add(13720);
                        }
                    }, 351876840);
                    put(new ArrayList<Integer>() {
                        {
                            add(15085);
                            add(28341);
                        }
                    }, 427523985);
                    put(new ArrayList<Integer>() {
                        {
                            add(-6311);
                            add(-16580);
                        }
                    }, 104636380);
                    put(new ArrayList<Integer>() {
                        {
                            add(23390);
                            add(5200);
                        }
                    }, 12162800);
                    put(new ArrayList<Integer>() {
                        {
                            add(-5991);
                            add(3518);
                        }
                    }, 21076338);
                    put(new ArrayList<Integer>() {
                        {
                            add(-11694);
                            add(-9482);
                        }
                    }, 55441254);
                    put(new ArrayList<Integer>() {
                        {
                            add(-27818);
                            add(-29107);
                        }
                    }, 809698526);
                    put(new ArrayList<Integer>() {
                        {
                            add(23630);
                            add(10221);
                        }
                    }, 241522230);
                    put(new ArrayList<Integer>() {
                        {
                            add(-18054);
                            add(7016);
                        }
                    }, 63333432);
                    put(new ArrayList<Integer>() {
                        {
                            add(24278);
                            add(5841);
                        }
                    }, 141807798);
                    put(new ArrayList<Integer>() {
                        {
                            add(27136);
                            add(-17364);
                        }
                    }, 117797376);
                    put(new ArrayList<Integer>() {
                        {
                            add(19533);
                            add(1832);
                        }
                    }, 35784456);
                    put(new ArrayList<Integer>() {
                        {
                            add(-25294);
                            add(25290);
                        }
                    }, 319842630);
                    put(new ArrayList<Integer>() {
                        {
                            add(28149);
                            add(29340);
                        }
                    }, 275297220);
                    put(new ArrayList<Integer>() {
                        {
                            add(-12825);
                            add(31176);
                        }
                    }, 44425800);
                    put(new ArrayList<Integer>() {
                        {
                            add(-21706);
                            add(-32595);
                        }
                    }, 707507070);
                    put(new ArrayList<Integer>() {
                        {
                            add(6402);
                            add(22980);
                        }
                    }, 24519660);
                    put(new ArrayList<Integer>() {
                        {
                            add(28376);
                            add(-7351);
                        }
                    }, 208591976);
                    put(new ArrayList<Integer>() {
                        {
                            add(29900);
                            add(-30580);
                        }
                    }, 45717100);
                    put(new ArrayList<Integer>() {
                        {
                            add(-30553);
                            add(20255);
                        }
                    }, 618851015);
                    put(new ArrayList<Integer>() {
                        {
                            add(14402);
                            add(16301);
                        }
                    }, 234767002);
                    put(new ArrayList<Integer>() {
                        {
                            add(-21221);
                            add(-17098);
                        }
                    }, 362836658);
                    put(new ArrayList<Integer>() {
                        {
                            add(-25138);
                            add(-32596);
                        }
                    }, 409699124);
                    put(new ArrayList<Integer>() {
                        {
                            add(2375);
                            add(11009);
                        }
                    }, 26146375);
                    put(new ArrayList<Integer>() {
                        {
                            add(-213);
                            add(-22916);
                        }
                    }, 4881108);
                    put(new ArrayList<Integer>() {
                        {
                            add(15358);
                            add(5599);
                        }
                    }, 85989442);
                    put(new ArrayList<Integer>() {
                        {
                            add(27365);
                            add(11824);
                        }
                    }, 323563760);
                    put(new ArrayList<Integer>() {
                        {
                            add(-29403);
                            add(-31719);
                        }
                    }, 310877919);
                    put(new ArrayList<Integer>() {
                        {
                            add(15628);
                            add(-17851);
                        }
                    }, 278975428);
                    put(new ArrayList<Integer>() {
                        {
                            add(-12577);
                            add(-9530);
                        }
                    }, 119858810);
                    put(new ArrayList<Integer>() {
                        {
                            add(11491);
                            add(26483);
                        }
                    }, 304316153);
                    put(new ArrayList<Integer>() {
                        {
                            add(15301);
                            add(5747);
                        }
                    }, 87934847);
                    put(new ArrayList<Integer>() {
                        {
                            add(24419);
                            add(19211);
                        }
                    }, 469113409);
                    put(new ArrayList<Integer>() {
                        {
                            add(28792);
                            add(-10329);
                        }
                    }, 297392568);
                    put(new ArrayList<Integer>() {
                        {
                            add(15269);
                            add(21712);
                        }
                    }, 331520528);
                    put(new ArrayList<Integer>() {
                        {
                            add(28129);
                            add(12986);
                        }
                    }, 365283194);
                    put(new ArrayList<Integer>() {
                        {
                            add(-14402);
                            add(22003);
                        }
                    }, 316887206);
                    put(new ArrayList<Integer>() {
                        {
                            add(-1049);
                            add(9436);
                        }
                    }, 9898364);
                    put(new ArrayList<Integer>() {
                        {
                            add(6716);
                            add(24175);
                        }
                    }, 162359300);
                    put(new ArrayList<Integer>() {
                        {
                            add(7199);
                            add(10558);
                        }
                    }, 76007042);
                    put(new ArrayList<Integer>() {
                        {
                            add(-28789);
                            add(17230);
                        }
                    }, 496034470);
                    put(new ArrayList<Integer>() {
                        {
                            add(822);
                            add(998);
                        }
                    }, 410178);
                    put(new ArrayList<Integer>() {
                        {
                            add(-28095);
                            add(1406);
                        }
                    }, 39501570);
                    put(new ArrayList<Integer>() {
                        {
                            add(-16407);
                            add(-29700);
                        }
                    }, 54143100);
                    put(new ArrayList<Integer>() {
                        {
                            add(-1897);
                            add(-6892);
                        }
                    }, 13074124);
                    put(new ArrayList<Integer>() {
                        {
                            add(-31727);
                            add(14704);
                        }
                    }, 466513808);
                    put(new ArrayList<Integer>() {
                        {
                            add(32749);
                            add(-6083);
                        }
                    }, 199212167);
                    put(new ArrayList<Integer>() {
                        {
                            add(8326);
                            add(-19379);
                        }
                    }, 161349554);
                    put(new ArrayList<Integer>() {
                        {
                            add(-6623);
                            add(-14486);
                        }
                    }, 95940778);
                    put(new ArrayList<Integer>() {
                        {
                            add(-21322);
                            add(-31641);
                        }
                    }, 674649402);
                    put(new ArrayList<Integer>() {
                        {
                            add(-30170);
                            add(-14230);
                        }
                    }, 42931910);
                    put(new ArrayList<Integer>() {
                        {
                            add(28451);
                            add(-8824);
                        }
                    }, 251051624);
                    put(new ArrayList<Integer>() {
                        {
                            add(3498);
                            add(32267);
                        }
                    }, 112869966);
                    put(new ArrayList<Integer>() {
                        {
                            add(-30891);
                            add(22366);
                        }
                    }, 690908106);
                    put(new ArrayList<Integer>() {
                        {
                            add(-16043);
                            add(29072);
                        }
                    }, 466402096);
                    put(new ArrayList<Integer>() {
                        {
                            add(27127);
                            add(-2239);
                        }
                    }, 60737353);
                    put(new ArrayList<Integer>() {
                        {
                            add(32093);
                            add(-5297);
                        }
                    }, 169996621);
                    put(new ArrayList<Integer>() {
                        {
                            add(-5796);
                            add(-19838);
                        }
                    }, 8212932);
                    put(new ArrayList<Integer>() {
                        {
                            add(3327);
                            add(5576);
                        }
                    }, 18551352);
                    put(new ArrayList<Integer>() {
                        {
                            add(12952);
                            add(-26558);
                        }
                    }, 171989608);
                    put(new ArrayList<Integer>() {
                        {
                            add(-1605);
                            add(-31690);
                        }
                    }, 10172490);
                    put(new ArrayList<Integer>() {
                        {
                            add(-13343);
                            add(13433);
                        }
                    }, 179236519);
                    put(new ArrayList<Integer>() {
                        {
                            add(27093);
                            add(-17062);
                        }
                    }, 462260766);
                    put(new ArrayList<Integer>() {
                        {
                            add(-8671);
                            add(-7851);
                        }
                    }, 68076021);
                    put(new ArrayList<Integer>() {
                        {
                            add(-7162);
                            add(-28184);
                        }
                    }, 100926904);
                    put(new ArrayList<Integer>() {
                        {
                            add(-1539);
                            add(-13712);
                        }
                    }, 21102768);
                    put(new ArrayList<Integer>() {
                        {
                            add(-16547);
                            add(-26794);
                        }
                    }, 443360318);
                    put(new ArrayList<Integer>() {
                        {
                            add(-27049);
                            add(-27368);
                        }
                    }, 67297912);
                    put(new ArrayList<Integer>() {
                        {
                            add(13440);
                            add(23381);
                        }
                    }, 314240640);
                    put(new ArrayList<Integer>() {
                        {
                            add(-3437);
                            add(-5978);
                        }
                    }, 2935198);
                    put(new ArrayList<Integer>() {
                        {
                            add(32475);
                            add(-17264);
                        }
                    }, 560648400);
                    put(new ArrayList<Integer>() {
                        {
                            add(26471);
                            add(-27743);
                        }
                    }, 734384953);
                    put(new ArrayList<Integer>() {
                        {
                            add(-15512);
                            add(1509);
                        }
                    }, 23407608);
                    put(new ArrayList<Integer>() {
                        {
                            add(12368);
                            add(19180);
                        }
                    }, 59304560);
                    put(new ArrayList<Integer>() {
                        {
                            add(-27237);
                            add(-9900);
                        }
                    }, 89882100);
                    put(new ArrayList<Integer>() {
                        {
                            add(-27467);
                            add(18849);
                        }
                    }, 517725483);
                    put(new ArrayList<Integer>() {
                        {
                            add(-11621);
                            add(-9140);
                        }
                    }, 106215940);
                    put(new ArrayList<Integer>() {
                        {
                            add(-16174);
                            add(-6247);
                        }
                    }, 101038978);
                    put(new ArrayList<Integer>() {
                        {
                            add(31379);
                            add(4571);
                        }
                    }, 143433409);
                    put(new ArrayList<Integer>() {
                        {
                            add(28611);
                            add(-11942);
                        }
                    }, 341672562);
                    put(new ArrayList<Integer>() {
                        {
                            add(-16701);
                            add(-10644);
                        }
                    }, 59255148);
                    put(new ArrayList<Integer>() {
                        {
                            add(28539);
                            add(9794);
                        }
                    }, 279510966);
                    put(new ArrayList<Integer>() {
                        {
                            add(-10030);
                            add(-15667);
                        }
                    }, 157140010);
                    put(new ArrayList<Integer>() {
                        {
                            add(19556);
                            add(-2604);
                        }
                    }, 12730956);
                    put(new ArrayList<Integer>() {
                        {
                            add(15347);
                            add(32007);
                        }
                    }, 491211429);
                    put(new ArrayList<Integer>() {
                        {
                            add(17309);
                            add(-16549);
                        }
                    }, 15076139);
                    put(new ArrayList<Integer>() {
                        {
                            add(-25001);
                            add(-26536);
                        }
                    }, 663426536);
                    put(new ArrayList<Integer>() {
                        {
                            add(14750);
                            add(-22443);
                        }
                    }, 331034250);
                    put(new ArrayList<Integer>() {
                        {
                            add(-9511);
                            add(28537);
                        }
                    }, 271415407);
                    put(new ArrayList<Integer>() {
                        {
                            add(16713);
                            add(-28209);
                        }
                    }, 157152339);
                    put(new ArrayList<Integer>() {
                        {
                            add(16653);
                            add(-759);
                        }
                    }, 4213209);
                    put(new ArrayList<Integer>() {
                        {
                            add(26567);
                            add(-13874);
                        }
                    }, 368590558);
                    put(new ArrayList<Integer>() {
                        {
                            add(23402);
                            add(-419);
                        }
                    }, 9805438);
                    put(new ArrayList<Integer>() {
                        {
                            add(16186);
                            add(14696);
                        }
                    }, 118934728);
                    put(new ArrayList<Integer>() {
                        {
                            add(-23208);
                            add(-30834);
                        }
                    }, 119265912);
                    put(new ArrayList<Integer>() {
                        {
                            add(10855);
                            add(-5070);
                        }
                    }, 846690);
                    put(new ArrayList<Integer>() {
                        {
                            add(-2862);
                            add(11842);
                        }
                    }, 16945902);
                    put(new ArrayList<Integer>() {
                        {
                            add(-2182);
                            add(-27670);
                        }
                    }, 30187970);
                    put(new ArrayList<Integer>() {
                        {
                            add(-269);
                            add(25727);
                        }
                    }, 6920563);
                    put(new ArrayList<Integer>() {
                        {
                            add(-15929);
                            add(5067);
                        }
                    }, 80712243);
                    put(new ArrayList<Integer>() {
                        {
                            add(28202);
                            add(31864);
                        }
                    }, 449314264);
                    put(new ArrayList<Integer>() {
                        {
                            add(13309);
                            add(-10546);
                        }
                    }, 140356714);
                    put(new ArrayList<Integer>() {
                        {
                            add(-9);
                            add(-160);
                        }
                    }, 1440);
                    put(new ArrayList<Integer>() {
                        {
                            add(-17626);
                            add(19912);
                        }
                    }, 175484456);
                    put(new ArrayList<Integer>() {
                        {
                            add(-29912);
                            add(-400);
                        }
                    }, 1495600);
                    put(new ArrayList<Integer>() {
                        {
                            add(-22998);
                            add(2776);
                        }
                    }, 31921224);
                    put(new ArrayList<Integer>() {
                        {
                            add(1345);
                            add(-21423);
                        }
                    }, 28813935);
                    put(new ArrayList<Integer>() {
                        {
                            add(12148);
                            add(5816);
                        }
                    }, 17663192);
                    put(new ArrayList<Integer>() {
                        {
                            add(1948);
                            add(28334);
                        }
                    }, 27597316);
                    put(new ArrayList<Integer>() {
                        {
                            add(28333);
                            add(9547);
                        }
                    }, 270495151);
                    put(new ArrayList<Integer>() {
                        {
                            add(3138);
                            add(-6627);
                        }
                    }, 6931842);
                    put(new ArrayList<Integer>() {
                        {
                            add(-10756);
                            add(-14551);
                        }
                    }, 156510556);
                    put(new ArrayList<Integer>() {
                        {
                            add(-9610);
                            add(-27484);
                        }
                    }, 132060620);
                    put(new ArrayList<Integer>() {
                        {
                            add(-331);
                            add(-31503);
                        }
                    }, 10427493);
                    put(new ArrayList<Integer>() {
                        {
                            add(20062);
                            add(27076);
                        }
                    }, 38799908);
                    put(new ArrayList<Integer>() {
                        {
                            add(-29540);
                            add(-5536);
                        }
                    }, 40883360);
                    put(new ArrayList<Integer>() {
                        {
                            add(11023);
                            add(-24251);
                        }
                    }, 267318773);
                    put(new ArrayList<Integer>() {
                        {
                            add(-15588);
                            add(10301);
                        }
                    }, 160571988);
                    put(new ArrayList<Integer>() {
                        {
                            add(30796);
                            add(5195);
                        }
                    }, 159985220);
                    put(new ArrayList<Integer>() {
                        {
                            add(29144);
                            add(-5722);
                        }
                    }, 83380984);
                    put(new ArrayList<Integer>() {
                        {
                            add(-4544);
                            add(21002);
                        }
                    }, 47716544);
                    put(new ArrayList<Integer>() {
                        {
                            add(30718);
                            add(24326);
                        }
                    }, 373623034);
                    put(new ArrayList<Integer>() {
                        {
                            add(-25355);
                            add(4918);
                        }
                    }, 124695890);
                    put(new ArrayList<Integer>() {
                        {
                            add(22543);
                            add(28030);
                        }
                    }, 631880290);
                    put(new ArrayList<Integer>() {
                        {
                            add(10774);
                            add(-32286);
                        }
                    }, 173924682);
                    put(new ArrayList<Integer>() {
                        {
                            add(14044);
                            add(-644);
                        }
                    }, 2261084);
                    put(new ArrayList<Integer>() {
                        {
                            add(-24430);
                            add(-20291);
                        }
                    }, 495709130);
                    put(new ArrayList<Integer>() {
                        {
                            add(-26623);
                            add(-8570);
                        }
                    }, 228159110);
                    put(new ArrayList<Integer>() {
                        {
                            add(1630);
                            add(-11100);
                        }
                    }, 1809300);
                    put(new ArrayList<Integer>() {
                        {
                            add(-25390);
                            add(4480);
                        }
                    }, 11374720);
                    put(new ArrayList<Integer>() {
                        {
                            add(-15501);
                            add(-18126);
                        }
                    }, 93657042);
                    put(new ArrayList<Integer>() {
                        {
                            add(-31331);
                            add(3272);
                        }
                    }, 102515032);
                    put(new ArrayList<Integer>() {
                        {
                            add(15333);
                            add(4705);
                        }
                    }, 72141765);
                    put(new ArrayList<Integer>() {
                        {
                            add(19818);
                            add(15974);
                        }
                    }, 158286366);
                    put(new ArrayList<Integer>() {
                        {
                            add(-16018);
                            add(13864);
                        }
                    }, 111036776);
                    put(new ArrayList<Integer>() {
                        {
                            add(20820);
                            add(-3675);
                        }
                    }, 5100900);
                    put(new ArrayList<Integer>() {
                        {
                            add(22094);
                            add(4311);
                        }
                    }, 95247234);
                    put(new ArrayList<Integer>() {
                        {
                            add(-27661);
                            add(5469);
                        }
                    }, 151278009);
                    put(new ArrayList<Integer>() {
                        {
                            add(-27301);
                            add(-31268);
                        }
                    }, 853647668);
                    put(new ArrayList<Integer>() {
                        {
                            add(5767);
                            add(-10528);
                        }
                    }, 60714976);
                    put(new ArrayList<Integer>() {
                        {
                            add(20946);
                            add(7601);
                        }
                    }, 159210546);
                    put(new ArrayList<Integer>() {
                        {
                            add(4086);
                            add(-22163);
                        }
                    }, 90558018);
                    put(new ArrayList<Integer>() {
                        {
                            add(-2219);
                            add(-15563);
                        }
                    }, 34534297);
                    put(new ArrayList<Integer>() {
                        {
                            add(-12380);
                            add(3196);
                        }
                    }, 9891620);
                    put(new ArrayList<Integer>() {
                        {
                            add(3726);
                            add(12323);
                        }
                    }, 45915498);
                    put(new ArrayList<Integer>() {
                        {
                            add(-15485);
                            add(-5491);
                        }
                    }, 4475165);
                    put(new ArrayList<Integer>() {
                        {
                            add(26241);
                            add(25216);
                        }
                    }, 661693056);
                    put(new ArrayList<Integer>() {
                        {
                            add(32400);
                            add(9396);
                        }
                    }, 939600);
                    put(new ArrayList<Integer>() {
                        {
                            add(5258);
                            add(-6843);
                        }
                    }, 35980494);
                    put(new ArrayList<Integer>() {
                        {
                            add(7294);
                            add(27264);
                        }
                    }, 99431808);
                    put(new ArrayList<Integer>() {
                        {
                            add(-18058);
                            add(-21182);
                        }
                    }, 191252278);
                    put(new ArrayList<Integer>() {
                        {
                            add(-1960);
                            add(-7660);
                        }
                    }, 750680);
                    put(new ArrayList<Integer>() {
                        {
                            add(-18430);
                            add(-27697);
                        }
                    }, 510455710);
                    put(new ArrayList<Integer>() {
                        {
                            add(-20340);
                            add(-10140);
                        }
                    }, 3437460);
                    put(new ArrayList<Integer>() {
                        {
                            add(24231);
                            add(13693);
                        }
                    }, 331795083);
                    put(new ArrayList<Integer>() {
                        {
                            add(22148);
                            add(-4912);
                        }
                    }, 27197744);
                    put(new ArrayList<Integer>() {
                        {
                            add(-32262);
                            add(16088);
                        }
                    }, 259515528);
                    put(new ArrayList<Integer>() {
                        {
                            add(-12692);
                            add(-31261);
                        }
                    }, 396764612);
                    put(new ArrayList<Integer>() {
                        {
                            add(8386);
                            add(15036);
                        }
                    }, 9006564);
                    put(new ArrayList<Integer>() {
                        {
                            add(17499);
                            add(22749);
                        }
                    }, 132694917);
                    put(new ArrayList<Integer>() {
                        {
                            add(26971);
                            add(9007);
                        }
                    }, 242927797);
                    put(new ArrayList<Integer>() {
                        {
                            add(6904);
                            add(-7107);
                        }
                    }, 49066728);
                    put(new ArrayList<Integer>() {
                        {
                            add(11217);
                            add(28479);
                        }
                    }, 106482981);
                    put(new ArrayList<Integer>() {
                        {
                            add(-24863);
                            add(-2847);
                        }
                    }, 70784961);
                    put(new ArrayList<Integer>() {
                        {
                            add(5101);
                            add(24458);
                        }
                    }, 124760258);
                    put(new ArrayList<Integer>() {
                        {
                            add(10360);
                            add(7271);
                        }
                    }, 75327560);
                    put(new ArrayList<Integer>() {
                        {
                            add(18863);
                            add(16366);
                        }
                    }, 308711858);
                    put(new ArrayList<Integer>() {
                        {
                            add(15651);
                            add(-25668);
                        }
                    }, 44636652);
                    put(new ArrayList<Integer>() {
                        {
                            add(-21657);
                            add(23977);
                        }
                    }, 519269889);
                    put(new ArrayList<Integer>() {
                        {
                            add(-15815);
                            add(-32149);
                        }
                    }, 508436435);
                    put(new ArrayList<Integer>() {
                        {
                            add(-25211);
                            add(-21865);
                        }
                    }, 551238515);
                    put(new ArrayList<Integer>() {
                        {
                            add(15056);
                            add(-7088);
                        }
                    }, 6669808);
                    put(new ArrayList<Integer>() {
                        {
                            add(2736);
                            add(-12642);
                        }
                    }, 5764752);
                    put(new ArrayList<Integer>() {
                        {
                            add(-27288);
                            add(17889);
                        }
                    }, 162718344);
                    put(new ArrayList<Integer>() {
                        {
                            add(16223);
                            add(-27692);
                        }
                    }, 449247316);
                    put(new ArrayList<Integer>() {
                        {
                            add(15598);
                            add(-14108);
                        }
                    }, 110028292);
                    put(new ArrayList<Integer>() {
                        {
                            add(31236);
                            add(7938);
                        }
                    }, 41325228);
                    put(new ArrayList<Integer>() {
                        {
                            add(-5279);
                            add(27729);
                        }
                    }, 146381391);
                    put(new ArrayList<Integer>() {
                        {
                            add(-22196);
                            add(7559);
                        }
                    }, 167779564);
                    put(new ArrayList<Integer>() {
                        {
                            add(-32332);
                            add(-13343);
                        }
                    }, 431405876);
                    put(new ArrayList<Integer>() {
                        {
                            add(-22839);
                            add(29043);
                        }
                    }, 221104359);
                    put(new ArrayList<Integer>() {
                        {
                            add(-24286);
                            add(31451);
                        }
                    }, 763818986);
                    put(new ArrayList<Integer>() {
                        {
                            add(-24619);
                            add(14063);
                        }
                    }, 49459571);
                    put(new ArrayList<Integer>() {
                        {
                            add(17616);
                            add(-23847);
                        }
                    }, 140029584);
                    put(new ArrayList<Integer>() {
                        {
                            add(-23693);
                            add(23906);
                        }
                    }, 566404858);
                    put(new ArrayList<Integer>() {
                        {
                            add(-11959);
                            add(30290);
                        }
                    }, 362238110);
                    /* END AUTOGENERATED CODE */
                }
            };
}
